/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wadosm_breweryhost_ConnectionConsumer */

#ifndef _Included_wadosm_breweryhost_ConnectionConsumer
#define _Included_wadosm_breweryhost_ConnectionConsumer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wadosm_breweryhost_ConnectionConsumer
 * Method:    attachListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wadosm_breweryhost_ConnectionConsumer_attachListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
