/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wadosm_breweryhost_DriverEntry */

#ifndef _Included_wadosm_breweryhost_DriverEntry
#define _Included_wadosm_breweryhost_DriverEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wadosm_breweryhost_DriverEntry
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wadosm_breweryhost_DriverEntry_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
