podTemplate(containers: [
    containerTemplate(name: 'orangepi-libs', image: 'localhost:32000/orangepi-libs', command: 'sleep', args: '99d')
  ]) {

  node(POD_LABEL) {
    stage('Build project') {
      git branch: 'main', credentialsId: '39c265c4-e80a-467d-bb0a-413825ac5cef', url: 'git@github.com:Michal-Wadowski/brewery-driver.git'

      container('orangepi-libs') {
        sh 'make clean && make REAL_IO=1'

        archiveArtifacts artifacts: 'brewery_driver.so', fingerprint: true

        sh 'make clean && make demo'

        archiveArtifacts artifacts: 'brewery_driver_demo.so', fingerprint: true
      }
    }
  }
}
